### ISSUE TITLE
perhaps two different versions of crate `bytes` are being used?

### ISSUE THREAD

**Issue by greenmughal** [quinn-rs/quinn#1004]
Im trying to create an independent project of connection example.

Here is what im getting.
 connection.send_datagram(bytes::Bytes::from("helloworld"));
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `bytes::bytes::Bytes`, found struct `bytes::Bytes`

```toml
[package]
name = "quinntest"
version = "0.1.0"
edition = "2018"
required-features = ["tls-rustls"]

[features]
default = ["native-certs", "certificate-transparency", "tls-rustls"]
# Use Google's list of CT logs to enable certificate transparency checks
certificate-transparency = ["quinn-proto/certificate-transparency"]
# Trust the contents of the OS certificate store by default
native-certs = ["quinn-proto/native-certs"]
tls-rustls = ["rustls", "webpki", "quinn-proto/tls-rustls"]

[dependencies]
quinn = "*"
tokio = { version = "0.2.6", features = ["rt-core", "io-driver", "time", "macros"] }
futures = "0.3.8"
rustls = { version = "0.19", features = ["quic"], optional = true }
quinn-proto = { version = "0.6.1" }
webpki = { version = "0.21", optional = true }
rcgen = "0.8"
bytes = "1.0.0" 

[dev-dependencies]
assert_matches = "1.1"
hex-literal = "0.3.0"
rcgen = "0.8"
tracing-subscriber = { version = "0.2.5", default-features = false, features = ["env-filter", "fmt", "ansi", "chrono"]}
lazy_static = "1"
tokio = { version = "0.2.6", features = ["rt-threaded", "time", "macros"] }
bytes = "1"
```
